-   id: go-imports
    name: 'go imports'
    entry: run-go-imports.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `goimports`, requires golang"
-   id: go-vet
    name: 'go vet'
    entry: run-go-vet.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go vet`, requires golang"
-   id: go-lint
    name: 'go lint'
    entry: run-go-lint.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `golint`, requires https://github.com/golang/lint"
-   id: go-unit-tests
    name: 'go-unit-tests'
    entry: run-go-unit-tests.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go test`"
-   id: go-mod-tidy
    name: 'go-mod-tidy'
    entry: run-go-mod-tidy.sh
    files: '\.go$'
    language: 'script'
    description: "Runs `go mod tidy -v`, requires golang"
-  id: golangci-lint
   name: 'go golangci-lint'
   entry: run-golangci-lint.sh
   files: '\.go$'
   language: 'script'
   description: "Runs `golangci-lint`, install https://github.com/golangci/golangci-lint"
